services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/usr/src/app:rw,cached"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    container_name: svelte-chat-app
    restart: unless-stopped
    networks:
      - svelte-chat-network

networks:
  svelte-chat-network:
    driver: bridge
